# Generated by Django 3.0.7 on 2020-06-18 17:37

import backend.assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.CharField(default=backend.assets.models.cutePk, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
