# Generated by Django 3.0.7 on 2020-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200618_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
