# Generated by Django 3.0.7 on 2020-06-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField()),
                ('category', models.CharField(max_length=36)),
                ('amount_in_cents', models.IntegerField()),
                ('is_transfer', models.BooleanField()),
                ('is_spending', models.BooleanField()),
                ('merchant', models.CharField(max_length=120)),
                ('internally_editted', models.BooleanField()),
                ('externally_editted', models.BooleanField()),
                ('json_blob', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.Account')),
            ],
        ),
    ]
