# Generated by Django 3.0.7 on 2020-07-07 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.BigIntegerField()),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=36)),
                ('amount_in_cents', models.IntegerField()),
                ('is_transfer', models.BooleanField()),
                ('is_spending', models.BooleanField()),
                ('merchant', models.CharField(max_length=120)),
                ('internally_editted', models.BooleanField(default=False)),
                ('externally_editted', models.BooleanField(default=False)),
                ('json_blob', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
