# Generated by Django 3.0.7 on 2020-06-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200618_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='effective_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='externally_editted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='internally_editted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='json_blob',
            field=models.TextField(blank=True, null=True),
        ),
    ]
